version: '3.7'

services:
  sandbox_bash:
    image: debian:bullseye-slim
    container_name: sandbox_bash
    environment:
      - LANG=C.UTF-8
    volumes:
      - ./malware_bash:/malware
    working_dir: /malware
    command: tail -f /dev/null  # Lancer le container sans interruption
    cap_add:
      - SYS_ADMIN  # Permet de manipuler certaines fonctionnalités du système dans le container
    security_opt:
      - seccomp=unconfined  # Désactive le seccomp pour tester certains malwares
    networks:
      - sandbox_net

  sandbox_python:
    image: python:3.9-slim
    container_name: sandbox_python
    environment:
      - LANG=C.UTF-8
    volumes:
      - ./malware_python:/malware
    working_dir: /malware
    command: tail -f /dev/null  # Lancer le container sans interruption
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    networks:
      - sandbox_net

  web_server:
    image: nginx:alpine
    container_name: web_server
    volumes:
      - ./web_content:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - sandbox_net
    restart: unless-stopped

networks:
  sandbox_net:
    driver: bridge

